# Generated by Django 4.2 on 2024-05-02 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiles',
            name='x_coordinates',
        ),
        migrations.RemoveField(
            model_name='tiles',
            name='y_coordinates',
        ),
    ]
