# Generated by Django 4.2 on 2024-05-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_tiles_x_coordinates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiles',
            name='house',
            field=models.CharField(choices=[('F', 'Fire'), ('W', 'Wood'), ('M', 'Metal'), ('E', 'Earth'), ('T', 'Water'), ('A', 'Admin')], default=None, max_length=1),
        ),
    ]
